
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhwisnseeutcmuqjtovh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpod2lzbnNlZXV0Y211cWp0b3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzcyOTYsImV4cCI6MjA1OTgxMzI5Nn0.9KnK-ivBDKBIalW1coA0DDvDB_I34hgIiloGnrs43RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add this type extension to ensure TypeScript recognizes the distance_preference property
declare module '@/integrations/supabase/types' {
  interface Tables {
    profiles: {
      Row: {
        distance_preference?: number;
      };
    };
  }
}
